name: Example skip job

on:
  push:
    branches:
      - "main"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job1"

  job2:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release' && needs.test-api.status == 'success'
    steps:
      - run: echo "job2"