name: Example automate cancel

on:
  push:
    branches:
      - "main"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job1 approved"
      - run: echo "Cancel job2"
  
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job2 approved"
      - run: echo "Cancel job1"
  
  job3:
    needs: [job1, job2]
    runs-on: ubuntu-latest
    if: | 
      always() && 
      ((needs.job1.result == 'success' && needs.job2.result == 'failure') || 
      (needs.job1.result == 'failure' && needs.job2.result == 'success'))
    steps:
      - run: echo "Job3 complete!"